/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddBook: typeof import('./src/components/Dialog/addBook.vue')['default']
    AddBookDialog: typeof import('./src/components/Dialog/BookDialog/AddBookDialog.vue')['default']
    AddUserDialog: typeof import('./src/components/Dialog/UserDialog/AddUserDialog.vue')['default']
    Book: typeof import('./src/components/Books/Book.vue')['default']
    Books: typeof import('./src/components/Books/Books.vue')['default']
    BooksList: typeof import('./src/components/Books/BooksList.vue')['default']
    Dasboard: typeof import('./src/components/dasboard.vue')['default']
    Dashboard: typeof import('./src/components/dashboard.vue')['default']
    DeleteBookDialog: typeof import('./src/components/Dialog/BookDialog/DeleteBookDialog.vue')['default']
    DeleteUserDialog: typeof import('./src/components/Dialog/UserDialog/DeleteUserDialog.vue')['default']
    EditBookDialog: typeof import('./src/components/Dialog/BookDialog/EditBookDialog.vue')['default']
    EditUserDialog: typeof import('./src/components/Dialog/UserDialog/EditUserDialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Login: typeof import('./src/components/login.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    User: typeof import('./src/components/Users/User.vue')['default']
    UsersList: typeof import('./src/components/Users/UsersList.vue')['default']
  }
}
